baseURL = 'https://palomaresss.github.io/portafolio/'
languageCode = 'en-us'
title = 'Portafolio'
theme = 'ananke'

[params]
  custom_css = ['custom.css']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
